### ISSUE TITLE
Choosing CMS platform

### ISSUE THREAD

**Issue by SunyataZero** [peoples-fund/peoples-fund#1]
Wordpress has more devs (7 to 1 on openhatch)
Drupal is more secure
We know people who might be able to help out with WP
We have more experiece with WP

**Comment by SunyataZero** [comment]
WordPress is more of a blogging platform

**Comment by SunyataZero** [comment]
> My personal anecdotes confirm much of the common wisdom.  WordPress is a great blogging platform, but beware when you step into deeper waters.  Joomla! is a decent option for low budget small business sites without a long range development path.  Drupal is still the king of robust and feature rich open source development environments.

https://www.commercialprogression.com/post/wordpress-joomla-and-drupal-why-i-jumped-ship-best-open-source-cms

**Comment by SunyataZero** [comment]
https://www.commercialprogression.com/post/wordpress-joomla-and-drupal-why-i-jumped-ship-best-open-source-cms

**Comment by SunyataZero** [comment]
http://www.arkhitech.com/wordpress-vs-joomla-vs-drupal/

http://trends.builtwith.com/cms

**Comment by frederikfederspiel** [comment]
Seems like wordpress is the way to go, if secure?

2016-01-09 8:45 GMT-05:00 Tord notifications@github.com:

**Comment by SunyataZero** [comment]
WordPress has now been chosen! _feeling of relief_
