### ISSUE TITLE
Adding https

### ISSUE THREAD

**Issue by SunyataZero** [peoples-fund/peoples-fund#17]
https://www.one.com/en/support/faq/how-do-i-manage-ssl-for-my-website

This will increase security and may even be required by Stripe (i've seen different information about whether it's required or not)

We could do this now but want to wait until we start accepting payments because of the cost

**Comment by frederikfederspiel** [comment]
super, let's get it, how much is it? 11.20 kr per month? If so: Let's!

2016-09-20 14:16 GMT+02:00 Tord notifications@github.com:
